work_dir: ./work_dir/ucla/bone6
# feeder
feeder: feeders.feeder_ucla.Feeder
# need set the datapath in line 20 in file feeder_ucla.py
train_feeder_args:
  data_path: bone
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False
  repeat: 5

test_feeder_args:
  data_path: bone
  label_path: val
  debug: False


# model
model: model.VerticalGroups_claster.Model
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: 'spatial'
  joint_label: [0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 2, 2, 2, 0, 2, 2, 2]

#optim
weight_decay: 0.000
base_lr: 0.025
lr_decay_rate: 0.1
step: [110, 120]

# training
device: 0
batch_size: 16
test_batch_size: 64
num_epoch: 150
nesterov: True
warm_up_epoch: 5
